# Week 2: Regression and model validation
This section is the report for the second week of IODS. To start with, here are the instructions given for writing this report:

>*Describe the work you have done this week and summarize your learning.*
>
>- Describe your work and results clearly. 
>- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods.
>- Assume the reader has no previous knowledge of your data or the more advanced methods you are using.

With that out of the way, let's start the analysis part of the current exercise set!

## The analysis data
The analysis data was produced in "Data wrangling" part. You can see the creation script [here](https://github.com/pkars/IODS-project/blob/master/data/create_learning2014.R) (most recent version) or the original from [commit `bb6de84`](https://github.com/pkars/IODS-project/blob/bb6de848b26bd4fbd3e909cce19831c8d86ccbee/data/create_learning2014.R)). The script stores the data to `learning2014.csv`, so let's start by reading that file.

```{r}
dset <- read.csv("data/learning2014.csv")
```


## Fitting the linear model

## Interpreting the model and the model diagnostics
